export interface Project {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  resolution: string;
  fps: number;
  thumbnailUri: string | null;
  timelineData: string; // JSON string of TimelineData
}

export interface TimelineData {
  duration: number;
  tracks: Track[];
}

export interface Track {
  id: string;
  type: 'video' | 'audio' | 'text' | 'sticker' | 'effect' | 'voiceover' | 'caption';
  isOverlay?: boolean;
  clips: Clip[];
}

export interface TextData {
  text: string;
  fontFamily?: string;
  fontSize?: number;
  color?: string;
  alignment?: 'left' | 'center' | 'right';
  backgroundColor?: string;
}

export interface CaptionData {
  style: 'clean' | 'bold' | 'karaoke' | 'highlight' | 'pop';
  autoGenerated: boolean;
}

export interface FilterData {
  id: string;
  name: string;
  intensity: number; // 0 to 1
}

export interface Adjustments {
  brightness?: number;
  contrast?: number;
  saturation?: number;
  exposure?: number;
  temperature?: number;
}

export interface EffectData {
  id: string;
  name: string;
  intensity: number;
  duration?: number;
}

export interface TransitionData {
  id: string;
  name: string;
  durationMs: number;
}

export interface KeyframeData {
  id: string;
  timeMs: number;
  property: 'position' | 'scale' | 'rotation' | 'opacity' | 'effect_intensity';
  value: number | { x: number; y: number };
}

export interface ChromaKeyData {
  enabled: boolean;
  colorHex: string;
  intensity: number;
  shadow: number;
}

export interface MaskData {
  type: 'none' | 'rectangle' | 'circle' | 'linear';
  feather: number;
  invert: boolean;
}

export interface Clip {
  id: string;
  mediaUri?: string;
  type: 'video' | 'image' | 'audio' | 'text' | 'sticker' | 'voiceover' | 'caption';
  start: number;
  duration: number;
  mediaStart: number;
  mediaDuration: number;

  // Phase 3
  textData?: TextData;
  filter?: FilterData;
  adjustments?: Adjustments;

  // Phase 4
  speed?: number;
  isReversed?: boolean;
  effect?: EffectData;
  transitionIn?: TransitionData;
  transitionOut?: TransitionData;

  // Phase 5
  keyframes?: KeyframeData[];
  chromaKey?: ChromaKeyData;
  mask?: MaskData;

  scale?: number;
  positionX?: number;
  positionY?: number;

  // Phase 6
  captionData?: CaptionData;
}

// Phase 6 Templates
export interface Template {
  id: string;
  name: string;
  thumbnailUri: string;
  description: string;
  expectedMediaCount: number;
  timelineDataBlueprint: TimelineData;
}
