import { useTimelineStore } from '../src/store/TimelineStore';
import { useProjectStore } from '../src/store/ProjectStore';
import { ProjectService } from '../src/database/ProjectService';
import { Template } from '../src/types/models';

jest.mock('../src/database/ProjectService', () => ({
  ProjectService: {
    updateProject: jest.fn().mockResolvedValue(undefined),
    createProject: jest.fn().mockResolvedValue(undefined),
    getAllProjects: jest.fn().mockResolvedValue([])
  }
}));

describe('TimelineStore and ProjectStore phase 6', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    useTimelineStore.setState({
      currentProject: { id: 'p1', name: 'Test', timelineData: '', thumbnailUri: null } as any,
      selectedClipId: null,
      timelineData: {
        duration: 2000,
        tracks: [
          {
            id: 'main',
            type: 'video',
            clips: [
              { id: 'c1', mediaUri: 'video.mp4', type: 'video', start: 0, duration: 2000, mediaStart: 0, mediaDuration: 2000 },
            ]
          }
        ]
      }
    });
  });

  it('adds voiceover to the timeline correctly', async () => {
    const store = useTimelineStore.getState();
    await store.addVoiceover('vo.m4a', 500, 3000);

    const newState = useTimelineStore.getState();
    const voTrack = newState.timelineData.tracks.find(t => t.type === 'voiceover');

    expect(voTrack).toBeDefined();
    expect(voTrack?.clips).toHaveLength(1);

    const voClip = voTrack?.clips[0];
    expect(voClip?.start).toBe(500);
    expect(voClip?.duration).toBe(3000);
    expect(voClip?.mediaUri).toBe('vo.m4a');

    // Overall timeline duration expands to fit the 3500ms end time
    expect(newState.timelineData.duration).toBe(3500);
  });

  it('generates a captions track from a list and styles them', async () => {
    const store = useTimelineStore.getState();
    const mockCaptions = [
      { text: "Line 1", start: 0, duration: 1000 },
      { text: "Line 2", start: 1000, duration: 1000 }
    ];
    await store.addCaptions(mockCaptions);

    const newState = useTimelineStore.getState();
    const captionTrack = newState.timelineData.tracks.find(t => t.type === 'caption');

    expect(captionTrack).toBeDefined();
    expect(captionTrack?.clips).toHaveLength(2);

    const c1 = captionTrack?.clips[0];
    expect(c1?.textData?.text).toBe("Line 1");
    expect(c1?.captionData?.autoGenerated).toBe(true);
    expect(c1?.start).toBe(0);
    expect(c1?.duration).toBe(1000);

    const c2 = captionTrack?.clips[1];
    expect(c2?.textData?.text).toBe("Line 2");
    expect(c2?.start).toBe(1000);
  });

  it('creates a project from a template blueprint successfully', async () => {
    const template: Template = {
      id: 't1',
      name: 'My Template',
      thumbnailUri: 'thumb.jpg',
      description: 'Test',
      expectedMediaCount: 1,
      timelineDataBlueprint: {
        duration: 5000,
        tracks: [
          { id: 'main', type: 'video', clips: [{ id: 'c1', type: 'video', start: 0, duration: 5000, mediaStart: 0, mediaDuration: 5000 }] }
        ]
      }
    };

    const newProject = await useProjectStore.getState().createProjectFromTemplate(template);

    expect(ProjectService.createProject).toHaveBeenCalledTimes(1);
    expect(newProject.name).toBe('My Template Project');

    // Validate blueprint copied
    const parsedData = JSON.parse(newProject.timelineData);
    expect(parsedData.duration).toBe(5000);
    expect(parsedData.tracks[0].clips).toHaveLength(1);
  });
});
